stages:
  - build

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"

before_script:
  - apt-get update && apt-get install -y tar

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore --no-cache
    - dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=false /p:EnableCompressionInSingleFile=true
    - tar -czvf publish.tar.gz -C bin/Release/net8.0/linux-x64/publish/ .
  artifacts:
    paths:
      - publish.tar.gz
