#
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: g7s
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    image: mcr.microsoft.com/dotnet/sdk:8.0
    script:
    - dotnet nuget add source https://pkgs.dev.azure.com/tgbots/Telegram.Bot/_packaging/release/nuget/v3/index.json -n Telegram.Bot
    - dotnet restore --no-cache
    - dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=false /p:EnableCompressionInSingleFile=true
    - tar -czvf publish.tar.gz -C bin/Release/net8.0/linux-x64/publish/ .
    artifacts:
      paths:
        - publish.tar.gz            
