image: mcr.microsoft.com/dotnet/sdk:8.0

jobs:
  build:
    runs-on: g7s
    steps:
      - uses: actions/checkout@v3
      - name: Setup telegram.bot
        run: dotnet nuget add source https://pkgs.dev.azure.com/tgbots/Telegram.Bot/_packaging/release/nuget/v3/index.json -n Telegram.Bot
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release
      - name: Publish
        run: dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=false /p:EnableCompressionInSingleFile=true
      - name: Create artifact
        run: tar -czvf publish.tar.gz publish
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish.tar.gz
          path: publish.tar.gz