kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
    commands:
      - dotnet nuget add source https://pkgs.dev.azure.com/tgbots/Telegram.Bot/_packaging/release/nuget/v3/index.json -n Telegram.Bot
      - dotnet restore --no-cache
      - dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=false /p:EnableCompressionInSingleFile=true
      - tar -czvf publish.tar.gz -C bin/Release/net8.0/linux-x64/publish/ .

services:
  - name: docker
    image: docker:dind

volumes:
  - name: dockersock
    path: /var/run/docker.sock

workspace:
  base: /drone/src
  path: github.com/your/repo

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
