name: release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ASPNETCORE_ENVIRONMENT: Production

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Log in to Container registry
        uses: docker/login-action@v2
        with:
          registry: git.mahdium.ir
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Cache for Docker
        uses: actions/cache@v4
        with:
          path: image-cache
          key: ${{ runner.os }}-image-cache-${{ github.ref }}-${{ github.sha }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: git.mahdium.ir/mahdium/cats-of-mastodon-telegram-bot
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: git.mahdium.ir/mahdium/cats-of-mastodon-telegram-bot${{gitea.sha}},git.mahdium.ir/mahdium/cats-of-mastodon-telegram-bot:latest
          labels: ${{ steps.meta.outputs.labels  }}
          cache-from: type=local,src=image-cache
          cache-to: type=local,dest=image-cache
